default_language_version:
    python: python3.7

default_stages: [commit, push]

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.0.1
  hooks:
    - id: trailing-whitespace
    - id: check-yaml
    - id: end-of-file-fixer

- repo: https://github.com/ansible/ansible-lint.git
  rev: v4.3.0a1
  hooks:
    - id: ansible-lint
      files: \.(yaml|yml)$
