default_language_version:
    python: python3.9

default_stages: [commit, push]

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: trailing-whitespace
    - id: check-yaml
    - id: end-of-file-fixer
    - id: check-added-large-files
    - id: check-merge-conflict

- repo: https://github.com/ansible/ansible-lint.git
  rev: v5.1.0a1
  hooks:
    - id: ansible-lint
      files: \.(yaml|yml)$
