- name: aervits.kerberos-server
  src: https://github.com/dbist/ansible-roles
  version: master

- name: aervits.jdk
  src: https://github.com/dbist/ansible-roles
  version: master

- name: aervits.devtools
  src: https://github.com/dbist/ansible-roles
  version: master
