---
# defaults file for aervits.kerberos-server

# role level variables
kerberos_server_hostname: node.example.com
realm: EXAMPLE.COM
master_db_pass: admin
admin_principal_password: admin

prerequisite_packages:
  - ntp

timezone: America/New_York
