---
# defaults file for aervits.kerberos-server
kerberos_server_hostname: krb.example.com
realm: EXAMPLE.COM
master_db_pass: admin
admin_principal_password: admin

prerequisite_packages:
  - ntp

kerberos_packages:
  - krb5-server
  - krb5-libs
  - krb5-workstation
