---
krb5kdc_dir: /etc/krb5kdc
principal_dir: /var/lib/krb5kdc
krb5_daemons:
  - krb5-admin-server
  - krb5-kdc

kerberos_packages:
  - krb5-kdc
  - krb5-admin-server
  - krb5-config

krb5_enc_types:
  - aes256-cts

  # these works but may not be compatible with CockroachDB
  #- camellia256-cts
  #- camellia128-cts
  
  # RHEL has these by default, remove the weak ones
  # des3-hmac-sha1:normal arcfour-hmac:normal camellia256-cts:normal camellia128-cts:normal des-hmac-sha1:normal des-cbc-md5:normal des-cbc-crc:normal