---
krb5kdc_dir: /etc/krb5kdc
principal_dir: /var/lib/krb5kdc
krb5_daemons:
  - krb5-admin-server
  - krb5-kdc

kerberos_packages:
  - krb5-kdc
  - krb5-admin-server
  - krb5-config

krb5_enc_types:
  - aes256-cts
  - aes128-cts
  - des3-hmac-sha1
  - arcfour-hmac
  - camellia256-cts
  - camellia128-cts
  
  # not supported
  #- des-cbc-md5
  #- des-hmac-sha1
  #- des-cbc-crc

  # RHEL has these by default
  # des3-hmac-sha1:normal arcfour-hmac:normal camellia256-cts:normal camellia128-cts:normal des-hmac-sha1:normal des-cbc-md5:normal des-cbc-crc:normal