---
# tasks file for aervits.kerberos-server

#- debug:
#    msg: debugging tasks

- name: kerberos requires ntp installed 
  include: ntp.yml

- name: starting kerberos provisioning
  include: kerberos.yml
